  const ships = [
    {
      "name": "USS Default",
      "nacelle_y": 40,
      "nacelle_x": 2.5,
      "nacelle_z": -3.5,
      "nacelle_length": 12,
      "nacelle_radius": 1,
      "nacelle_widthRatio": 1,
      "engineering_y": -25,
      "engineering_z": 6,
      "engineering_length": 10,
      "engineering_radius": 1,
      "engineering_widthRatio": 1,
      "pylon_nacelleForeOffset": 0.3,
      "pylon_nacelleAftOffset": 0.3,
      "pylon_engineeringForeOffset": 0.3,
      "pylon_engineeringAftOffset": 0.3,
      "neck_primaryForeOffset": 0.3,
      "neck_primaryAftOffset": 0.3,
      "neck_engineeringForeOffset": 0.3,
      "neck_engineeringAftOffset": 0.3,
      "primary_y": -10,
      "primary_z": 0.5,
      "primary_radius": 12,
      "primary_thickness": 4,
      "primary_widthRatio": 1
    },
    {
      "name": "USS Unreliantable",
      "nacelle_y": 40,
      "nacelle_x": 12.5,
      "nacelle_z": -3.5,
      "nacelle_length": 22,
      "nacelle_radius": 1,
      "nacelle_widthRatio": 1,
      "engineering_y": -25,
      "engineering_z": 6,
      "engineering_length": 10,
      "engineering_radius": 1,
      "engineering_widthRatio": 1,
      "pylon_nacelleForeOffset": 0.3,
      "pylon_nacelleAftOffset": 0.3,
      "pylon_engineeringForeOffset": 0.3,
      "pylon_engineeringAftOffset": 0.3,
      "neck_primaryForeOffset": 0.3,
      "neck_primaryAftOffset": 0.3,
      "neck_engineeringForeOffset": 0.3,
      "neck_engineeringAftOffset": 0.3,
      "primary_y": -10,
      "primary_z": -0.5,
      "primary_radius": 10,
      "primary_thickness": 8,
      "primary_widthRatio": 1
    }
  ]
  export default ships;