  const ships = [
    {
      "name": "USS Defaultant",
      "nacelle_lowerToggle": false,
      "nacelle_y": 26.5,
      "nacelle_x": 3.4,
      "nacelle_z": -0.8,
      "nacelle_length": 22.3,
      "nacelle_radius": 1.32,
      "nacelle_widthRatio": 1,
      "nacelle_rotation": 0,
      "engineering_y": -28.9,
      "engineering_z": 7.6,
      "engineering_length": 15.3,
      "engineering_radius": 1.8,
      "engineering_widthRatio": 1,
      "engineering_skew": 0,
      "pylon_nacelleForeOffset": 0.21,
      "pylon_nacelleAftOffset": 0.45,
      "pylon_engineeringForeOffset": 0.56,
      "pylon_engineeringAftOffset": 0.19,
      "pylon_thickness": 0.3,
      "neck_primaryForeOffset": 0.39,
      "neck_primaryAftOffset": 0.15,
      "neck_engineeringForeOffset": 0.36,
      "neck_engineeringAftOffset": 0.08,
      "neck_thickness": 0.3,
      "primary_y": -10,
      "primary_z": 0.5,
      "primary_radius": 12,
      "primary_thickness": 4,
      "primary_widthRatio": 1
    },
    {
      "name": "USS Unreliantable",
      "nacelle_lowerToggle": false,
      "nacelle_y": 10.7,
      "nacelle_x": 5.5,
      "nacelle_z": -5.6,
      "nacelle_length": 28.1,
      "nacelle_radius": 1.32,
      "nacelle_widthRatio": 1,
      "nacelle_rotation": 0,
      "engineering_y": -31,
      "engineering_z": 3.87,
      "engineering_length": 21.76,
      "engineering_radius": 2.68,
      "engineering_widthRatio": 1,
      "engineering_skew": 0,
      "pylon_nacelleForeOffset": 0.4,
      "pylon_nacelleAftOffset": 0.58,
      "pylon_engineeringForeOffset": 0.03,
      "pylon_engineeringAftOffset": 0.13,
      "pylon_thickness": 0.3,
      "neck_primaryForeOffset": 0.39,
      "neck_primaryAftOffset": 0.15,
      "neck_engineeringForeOffset": 0.36,
      "neck_engineeringAftOffset": 0.08,
      "neck_thickness": 0.3,
      "primary_y": -10,
      "primary_z": 0.5,
      "primary_radius": 12,
      "primary_thickness": 3.5,
      "primary_widthRatio": 1
    },
    {
      "nacelle_lowerToggle": false,
      "nacelle_y": 19.3,
      "nacelle_x": 3.4,
      "nacelle_z": -5.8,
      "nacelle_length": 19.8,
      "nacelle_radius": 1.25,
      "nacelle_widthRatio": 1,
      "nacelle_rotation": 0,
      "engineering_y": -35.2,
      "engineering_z": 6.5,
      "engineering_length": 29.2,
      "engineering_radius": 1.7,
      "engineering_widthRatio": 1.6,
      "engineering_skew": 0,
      "pylon_nacelleForeOffset": 0.61,
      "pylon_nacelleAftOffset": 0.25,
      "pylon_engineeringForeOffset": 0.4,
      "pylon_engineeringAftOffset": 0,
      "pylon_thickness": 0.3,
      "neck_primaryForeOffset": 0,
      "neck_primaryAftOffset": 0,
      "neck_engineeringForeOffset": 0,
      "neck_engineeringAftOffset": 0,
      "primary_y": -2.4,
      "necktThicknes": 0.1,
      "primary_z": 0.7,
      "primary_radius": 18.1,
      "primary_thickness": 4.8,
      "primary_widthRatio": 0.5,
      "name": "USS Jauntinger"
    },
    {
      "name": "USS Earlgrey",
      "nacelle_lowerToggle": false,
      "nacelle_y": 26.32,
      "nacelle_x": 3.4,
      "nacelle_z": -4.87,
      "nacelle_length": 13.17,
      "nacelle_radius": 0.85,
      "nacelle_widthRatio": 1.95,
      "nacelle_rotation": 0,
      "engineering_y": -38.9,
      "engineering_z": 7.6,
      "engineering_length": 16.2,
      "engineering_radius": 1.61,
      "engineering_widthRatio": 2.44,
      "engineering_skew": -0.7,
      "pylon_nacelleForeOffset": 0.39,
      "pylon_nacelleAftOffset": 0.27,
      "pylon_engineeringForeOffset": 0.69,
      "pylon_engineeringAftOffset": 0,
      "pylon_thickness": 0.3,
      "neck_primaryForeOffset": 0.65,
      "neck_primaryAftOffset": 0,
      "neck_engineeringForeOffset": 0.1,
      "neck_engineeringAftOffset": 0.19,
      "neck_thickness": 0.3,
      "primary_y": -14.32,
      "primary_z": 1.08,
      "primary_radius": 12,
      "primary_thickness": 4,
      "primary_widthRatio": 1.3
    },
    {
      "name": "NX Warpington",
      "nacelle_lowerToggle": false,
      "nacelle_y": 26.5,
      "nacelle_x": 5.47,
      "nacelle_z": 0.2,
      "nacelle_length": 14.94,
      "nacelle_radius": 1.32,
      "nacelle_widthRatio": 1,
      "nacelle_rotation": 0,
      "engineering_y": -31.27,
      "engineering_z": 2.31,
      "engineering_length": 28.52,
      "engineering_radius": 0.95,
      "engineering_widthRatio": 7.48,
      "engineering_skew": 0,
      "pylon_nacelleForeOffset": 0.38,
      "pylon_nacelleAftOffset": 0.27,
      "pylon_engineeringForeOffset": 0.82,
      "pylon_engineeringAftOffset": 0,
      "pylon_thickness": 0.3,
      "neck_primaryForeOffset": 0.39,
      "neck_primaryAftOffset": 0.15,
      "neck_engineeringForeOffset": 0.36,
      "neck_engineeringAftOffset": 0.08,
      "neck_thickness": 0.3,
      "primary_y": -14.32,
      "primary_z": 0.5,
      "primary_radius": 12,
      "primary_thickness": 4,
      "primary_widthRatio": 1
    },
    {
      "name": "USS Celcius",
      "nacelle_lowerToggle": false,
      "nacelle_y": 10.2,
      "nacelle_x": 0,
      "nacelle_z": -6.64,
      "nacelle_length": 28.62,
      "nacelle_radius": 1.71,
      "nacelle_widthRatio": 1.0,
      "nacelle_rotation": 0,
      "engineering_y": -37.58,
      "engineering_z": -1.9,
      "engineering_length": 23.05,
      "engineering_radius": 2.2,
      "engineering_widthRatio": 1,
      "engineering_skew": 0,
      "pylon_nacelleForeOffset": 1,
      "pylon_nacelleAftOffset": 0.45,
      "pylon_engineeringForeOffset": 0.11,
      "pylon_engineeringAftOffset": 1,
      "pylon_thickness": 0.3,
      "neck_primaryForeOffset": 0.39,
      "neck_primaryAftOffset": 0.15,
      "neck_engineeringForeOffset": 0.36,
      "neck_engineeringAftOffset": 0.08,
      "neck_thickness": 0.3,
      "primary_y": -10,
      "primary_z": 0.5,
      "primary_radius": 14.81,
      "primary_thickness": 4,
      "primary_widthRatio": 1.0
    },
    {
      "name": "Sparrow of Prey",
      "nacelle_lowerToggle": false,
      "nacelle_y": 5.94,
      "nacelle_x": 11.27,
      "nacelle_z": -17.52,
      "nacelle_length": 22.3,
      "nacelle_radius": 1.32,
      "nacelle_widthRatio": 1,
      "nacelle_rotation": 0,
      "engineering_y": -28.9,
      "engineering_z": 7.6,
      "engineering_length": 17.46,
      "engineering_radius": 2.96,
      "engineering_widthRatio": 2.37,
      "engineering_skew": -0.5,
      "pylon_nacelleForeOffset": 0.14,
      "pylon_nacelleAftOffset": 0.65,
      "pylon_engineeringForeOffset": 0.11,
      "pylon_engineeringAftOffset": 0,
      "pylon_thickness": 0.3,
      "neck_primaryForeOffset": 0,
      "neck_primaryAftOffset": 0,
      "neck_engineeringForeOffset": 0,
      "neck_engineeringAftOffset": 0,
      "primary_y": 9.13,
      "necktThicknes": 0.1,
      "primary_z": 8.6,
      "primary_radius": 7.75,
      "primary_thickness": 5.11,
      "primary_widthRatio": 0.36,
    },
    {
      "name": "IKS Jeffkaaa",
      "nacelle_lowerToggle": false,
      "nacelle_y": 23,
      "nacelle_x": 9.7,
      "nacelle_z": -13.5,
      "nacelle_length": 19.5,
      "nacelle_radius": 2.25,
      "nacelle_widthRatio": 0.4,
      "nacelle_rotation": 0,
      "engineering_y": -32,
      "engineering_z": 6,
      "engineering_length": 19.5,
      "engineering_radius": 2.07,
      "engineering_widthRatio": 3.25,
      "engineering_skew": 1.15,
      "pylon_nacelleForeOffset": 0.16,
      "pylon_nacelleAftOffset": 0.13,
      "pylon_engineeringForeOffset": 0.21,
      "pylon_engineeringAftOffset": 0.41,
      "pylon_thickness": 0.78,
      "neck_primaryForeOffset": 0.08,
      "neck_primaryAftOffset": 0,
      "neck_engineeringForeOffset": 0.19,
      "neck_engineeringAftOffset": 0,
      "neck_thickness": 0.94,
      "primary_y": 13.9,
      "primary_z": 6.47,
      "primary_radius": 6.8,
      "primary_thickness": 8.2,
      "primary_widthRatio": 0.68,
    },
    {
      "name": "RSI Cloaked Canary",
      "nacelle_y": -5.47,
      "nacelle_x": 12.33,
      "nacelle_z": 1.78,
      "nacelle_length": 28.1,
      "nacelle_radius": 2.4,
      "nacelle_widthRatio": 1,
      "nacelle_rotation": 0,
      "engineering_y": -28.5,
      "engineering_z": 4.21,
      "engineering_length": 30.46,
      "engineering_radius": 2.0,
      "engineering_widthRatio": 3.71,
      "engineering_skew": 0,
      "pylon_nacelleForeOffset": 0,
      "pylon_nacelleAftOffset": 0.66,
      "pylon_engineeringForeOffset": 0.12,
      "pylon_engineeringAftOffset": 0.18,
      "pylon_thickness": 0.3,
      "neck_primaryForeOffset": 0.39,
      "neck_primaryAftOffset": 0.15,
      "neck_engineeringForeOffset": 0,
      "neck_engineeringAftOffset": 0,
      "primary_y": -6.33,
      "neck_thickness": 0.1,
      "primary_z": 2.74,
      "primary_radius": 13.09,
      "primary_thickness": 4.98,
      "primary_widthRatio": 0.88,
    },
    {
      "name": "USS McQuarrie Fever",
      "nacelle_lowerToggle": false,
      "nacelle_y": 26.19,
      "nacelle_x": 5.94,
      "nacelle_z": -7.83,
      "nacelle_length": 35.42,
      "nacelle_radius": 0.86,
      "nacelle_widthRatio": 1.97,
      "nacelle_rotation": 0,
      "engineering_y": -37.28,
      "engineering_z": 6.5,
      "engineering_length": 26.93,
      "engineering_radius": 1.49,
      "engineering_widthRatio": 1.6,
      "engineering_skew": 0,
      "pylon_nacelleForeOffset": 0.31,
      "pylon_nacelleAftOffset": 0.6,
      "pylon_engineeringForeOffset": 0.04,
      "pylon_engineeringAftOffset": 0.18,
      "pylon_thickness": 0.3,
      "neck_primaryForeOffset": 0.6,
      "neck_primaryAftOffset": 0.04,
      "neck_engineeringForeOffset": 0.1,
      "neck_engineeringAftOffset": 0.13,
      "neck_thickness": 1.17,
      "primary_y": -2.14,
      "primary_z": 1.58,
      "primary_radius": 13.06,
      "primary_thickness": 3.36,
      "primary_widthRatio": 1,
    },
    {
      "name": "USS Jeaves",
      "nacelle_lowerToggle": false,
      "nacelle_y": 9.76,
      "nacelle_x": 7.71,
      "nacelle_z": -7.83,
      "nacelle_length": 35.42,
      "nacelle_radius": 0.86,
      "nacelle_widthRatio": 2.47,
      "nacelle_rotation": -0.94,
      "engineering_y": -31.53,
      "engineering_z": 2.09,
      "engineering_length": 40.45,
      "engineering_radius": 1.19,
      "engineering_widthRatio": 3.32,
      "engineering_skew": 2,
      "pylon_nacelleForeOffset": 0.21,
      "pylon_nacelleAftOffset": 0.58,
      "pylon_engineeringForeOffset": 0.36,
      "pylon_engineeringAftOffset": 0.2,
      "pylon_thickness": 0.45,
      "neck_primaryForeOffset": 0.6,
      "neck_primaryAftOffset": 0.04,
      "neck_engineeringForeOffset": 0.06,
      "neck_engineeringAftOffset": 0,
      "neck_thickness": 0.3,
      "primary_y": -2.19,
      "primary_z": 1.6,
      "primary_radius": 13.06,
      "primary_thickness": 3.02,
      "primary_widthRatio": 1,
    },
    {
      "name": "USS Insolent",
      "nacelle_lowerToggle": false,
      "nacelle_y": 18.22,
      "nacelle_x": 4.17,
      "nacelle_z": -2.89,
      "nacelle_length": 7.58,
      "nacelle_radius": 1.01,
      "nacelle_widthRatio": 2.93,
      "nacelle_rotation": -0.34,
      "engineering_y": -28.9,
      "engineering_z": 2.2,
      "engineering_length": 18.86,
      "engineering_radius": 1.21,
      "engineering_widthRatio": 2.99,
      "engineering_skew": -0.83,
      "pylon_nacelleForeOffset": 0.21,
      "pylon_nacelleAftOffset": 0.45,
      "pylon_engineeringForeOffset": 0.56,
      "pylon_engineeringAftOffset": 0.19,
      "pylon_thickness": 0.3,
      "neck_primaryForeOffset": 0.39,
      "neck_primaryAftOffset": 0.15,
      "neck_engineeringForeOffset": 0.36,
      "neck_engineeringAftOffset": 0.08,
      "neck_thickness": 0.3,
      "primary_y": -21.37,
      "primary_z": 0.5,
      "primary_radius": 7.94,
      "primary_thickness": 3.27,
      "primary_widthRatio": 1,
    },
    {
      "nacelle_lowerToggle": false,
      "nacelle_y": 10.2,
      "nacelle_x": 5.47,
      "nacelle_z": -6.64,
      "nacelle_length": 28.62,
      "nacelle_radius": 1.71,
      "nacelle_widthRatio": 1,
      "nacelle_rotation": 0,
      "engineering_y": -27.53,
      "engineering_z": -2.08,
      "engineering_length": 12.56,
      "engineering_radius": 2.2,
      "engineering_widthRatio": 2.37,
      "engineering_skew": 0,
      "pylon_nacelleForeOffset": 1,
      "pylon_nacelleAftOffset": 0.45,
      "pylon_engineeringForeOffset": 0.21,
      "pylon_engineeringAftOffset": 0.86,
      "pylon_thickness": 0.3,
      "neck_primaryForeOffset": 0.12,
      "neck_primaryAftOffset": 0.18,
      "neck_engineeringForeOffset": 0.62,
      "neck_engineeringAftOffset": 0.08,
      "neck_thickness": 0.3,
      "primary_y": -10,
      "primary_z": 0.5,
      "primary_radius": 14.81,
      "primary_thickness": 4,
      "primary_widthRatio": 1,
      "name": 'USS Gloucester',
    },
    {
      "name": "USS Smallstepper",
      "nacelle_lowerToggle": true,
      "nacelle_y": 9.68,
      "nacelle_x": 4.94,
      "nacelle_z": 2.81,
      "nacelle_length": 35.42,
      "nacelle_radius": 0.86,
      "nacelle_widthRatio": 2.47,
      "nacelle_rotation": -0.94,
      "nacelleLower_y": 9.68,
      "nacelleLower_x": 4.94,
      "nacelleLower_z": 6.76,
      "nacelleLower_length": 35.42,
      "nacelleLower_radius": 0.86,
      "nacelleLower_widthRatio": 2.47,
      "nacelleLower_rotation": 0.94,
      "engineering_y": -22.89,
      "engineering_z": 2.09,
      "engineering_length": 22.03,
      "engineering_radius": 1.83,
      "engineering_widthRatio": 3.32,
      "engineering_skew": 2,
      "pylon_nacelleForeOffset": 0.19,
      "pylon_nacelleAftOffset": 0.5,
      "pylon_engineeringForeOffset": 0.44,
      "pylon_engineeringAftOffset": 0.31,
      "pylon_thickness": 0.45,
      "neck_primaryForeOffset": 0.6,
      "neck_primaryAftOffset": 0.04,
      "neck_engineeringForeOffset": 0.06,
      "neck_engineeringAftOffset": 0,
      "neck_thickness": 0.3,
      "primary_y": -2.19,
      "primary_z": 0.74,
      "primary_radius": 13.06,
      "primary_thickness": 3.02,
      "primary_widthRatio": 1,
    },
  ]
  export default ships;